#!/usr/bin/env python3
"""
image_pipeline.py — concept-aware LP image generation via Gemini nano-banana-pro-preview.

Part of mgc-saiyo-lp-bootstrap. Replaces the v0 approach (raw scrape URLs
from the client's site reused verbatim) with concept-aware image generation
that KEEPS the style from the reference site (colors via theme tokens) but
GENERATES new imagery based on what the company actually does and values.

This enforces RULE 14 from SKILL.md: "Images should be 融合 of original
style + generated content, NOT reused homepage photos."

═══ How it's used from bootstrap.py ═══

    from image_pipeline import ImagePipeline, ImageSpec

    pipe = ImagePipeline(
        slug='cloq',
        client_name='株式会社CLOQ',
        industry='採用コンサルティング',
        theme_accent='#2673b8',
        company_concepts={
            'business_type': '人材紹介事業 / 採用コンサルティング',
            'values': ['本音', 'フラットチーム', '在宅可・服装自由'],
            'location_hint': 'Kyoto',
            'culture_tone': 'young, honest, hands-on',
        },
        openings=[
            {'title': '採用支援スタッフ', 'en': 'Recruitment Support', 'employee_name': '田中 美咲'},
            {'title': '採用クリエイター', 'en': 'Recruitment Writer', 'employee_name': '佐藤 健太'},
        ],
    )
    urls = pipe.generate_all()  # blocks for ~20-25s total (parallel)
    # urls is a dict keyed by slot path:
    # { 'hero.bg_image': 'https://mgc-pass-proxy.duckdns.org/img/cloq_hero_*.jpg',
    #   'about.photo': '...',
    #   'openings.items.0.image': '...',
    #   'openings.items.0.detail.hero_bg': '...',  # same URL as .image
    #   'openings.items.0.detail.employee.photo': '...',
    #   ...
    # }

The caller (bootstrap.py) then builds a single UPDATE statement that
jsonb_sets each path into lp_content. No Supabase Storage calls — images
are written directly to /home/ubuntu/github-proxy/uploads/slides/ and
served via nginx at mgc-pass-proxy.duckdns.org/img/.

═══ Parallelism ═══

All generations run in parallel via ThreadPoolExecutor(max_workers=6).
Empirical timings on Gemini nano-banana-pro-preview: ~20-22s per image,
parallel wall time matches the slowest single call. For a 2-opening LP
with 2 placeholder employees, total generation time is ~22s wall clock
vs ~130s sequential.

═══ Infrastructure dependencies ═══

- GEMINI_API_KEY must be set in Doppler nippo-syncro-kun/dev
- /home/ubuntu/github-proxy/uploads/slides/ must be writable as the
  executing user (Jayden's ubuntu account works)
- nginx must serve /img/ from that path (see /etc/nginx/sites-enabled/
  mgc-proxy line 81 — alias directive)
- Python 3.8+ (uses concurrent.futures, no external deps beyond stdlib)

═══ Why not Supabase Storage? ═══

See SKILL.md categories 10-12 and the hand-off notes in the cloq build
retrospective. Short version: the lp-images bucket exists in
pglaffdnhixmabcjdxbi but (a) the service_role key in Vercel env is
broken/stale, (b) the anon key in Doppler is for a different project
(isp-approach-bot), and (c) upload/route.ts ALREADY routes through
mgc-pass-proxy for the admin editor's uploads. Keeping image generation
on the same path is architecturally consistent — all LP images live at
mgc-pass-proxy.duckdns.org/img/ regardless of whether they were
AI-generated by this skill or uploaded manually by a client via the
admin editor. One storage path, one set of public URLs, one backup target.
"""
from __future__ import annotations
import os
import sys
import json
import time
import base64
import urllib.request
import urllib.error
import subprocess
import hashlib
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Optional

# ─── Config ────────────────────────────────────────────────────────────
OUTPUT_DIR = "/home/ubuntu/github-proxy/uploads/slides"
PUBLIC_BASE = "https://mgc-pass-proxy.duckdns.org/img"
MODEL = "nano-banana-pro-preview"
API_BASE = "https://generativelanguage.googleapis.com/v1beta"
REQUEST_TIMEOUT_SEC = 180


def _get_gemini_key() -> str:
    """Read GEMINI_API_KEY from Doppler. Raises RuntimeError if missing."""
    try:
        result = subprocess.run(
            ["doppler", "secrets", "get", "GEMINI_API_KEY",
             "--project", "nippo-syncro-kun", "--config", "dev", "--plain"],
            capture_output=True, text=True, check=True,
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"Could not read GEMINI_API_KEY from Doppler: {e.stderr.strip()}"
        ) from e
    key = result.stdout.strip()
    if not key:
        raise RuntimeError("GEMINI_API_KEY is empty in Doppler nippo-syncro-kun/dev")
    return key


# ─── Prompt templates ──────────────────────────────────────────────────
# These are general templates. The ImagePipeline class fills in the
# client-specific details (company_concepts, openings, etc.) when building
# the final prompts so each client gets something unique that matches
# their actual business.
#
# Style directives are shared across all prompts:
#   - Japanese setting (assumed location_hint default = "Kyoto, Japan")
#   - Modern minimalist aesthetic
#   - Natural photography style (NOT illustration, NOT 3D render)
#   - Subtle theme_accent color wash in shadows
#   - Explicit AI-failure exclusions: no text overlays, no readable logos,
#     no watermarks, realistic hands with correct fingers, not "AI-rendered"
#     look

_SHARED_STYLE_BLOCK = (
    "Editorial magazine photography style, shallow depth of field, soft "
    "natural lighting, photojournalism quality. NO text overlays, NO "
    "visible logos or brand names, NO watermarks, realistic skin texture, "
    "realistic human hands with correct finger counts, NOT an AI-rendered "
    "look."
)

HERO_PROMPT_TEMPLATE = (
    "A wide cinematic 16:9 photograph of a bright, modern creative office "
    "in {location_hint}, in early morning light streaming through large "
    "windows. A diverse team of 4-5 young Japanese professionals in their "
    "20s and early 30s, dressed in smart casual attire (no suits, no ties), "
    "gathered around a long wooden table with open laptops, notebooks, and "
    "coffee cups. They are in the middle of a genuine working collaboration "
    "on {business_type_en} work — one person at a whiteboard sketching a "
    "{business_workflow} diagram, others engaged in honest discussion, "
    "pointing at the screen. The atmosphere is warm, focused, and flat "
    "(no visible hierarchy). Background includes natural wooden accents, "
    "minimalist indoor plants, simple shoji-inspired screen dividers, and "
    "a glimpse of a traditional {location_hint} rooftop through the window "
    "blending old and new. Subtle cool accent color ({theme_accent}) in the "
    "shadows. {style}"
)

ABOUT_PROMPT_TEMPLATE = (
    "A 4:3 editorial photograph of two young Japanese professionals — a "
    "woman and a man in their late 20s — sitting across from each other "
    "at a light oak wooden table in a quiet {location_hint} cafe corner. "
    "They are having a genuine candid {conversation_topic} conversation, "
    "both leaning slightly forward, engaged. The woman is gesturing "
    "mid-sentence with an open notebook in front of her, the man is "
    "listening attentively while nodding. Both are dressed in smart casual "
    "business attire, no suits. Natural afternoon light from a large "
    "window to the side, warm atmosphere, a ceramic coffee cup and a "
    "laptop lightly visible at the edge of frame. The composition "
    "represents {values_en} — two equals talking, not a manager briefing "
    "a subordinate. Background softly blurred with a glimpse of a wooden "
    "{location_hint} cafe interior. Subtle cool accent color "
    "({theme_accent}) in the window light. {style}"
)

POSITION_PROMPT_TEMPLATE = (
    "A 16:9 photograph of a young Japanese {gender} in their late 20s "
    "working at a modern minimalist office desk in {location_hint}, "
    "depicting the role of {role_name} ({role_en}) — {role_action}. "
    "{environment_detail} Soft directional window light from the {light_side} "
    "side, clean minimalist background with warm beige walls. They are "
    "dressed in {outfit}, smart casual. Editorial office photography style, "
    "warm tones with a subtle cool accent ({theme_accent}) in the wall "
    "shadow. {style}"
)

EMPLOYEE_HEADSHOT_TEMPLATE = (
    "A 4:5 portrait-orientation professional headshot photograph of a "
    "young Japanese {gender} in their late 20s, {expression}, {gaze}. "
    "{hair_desc}, {appearance_detail}. They are wearing {outfit} — smart "
    "casual, no suit. The background is a softly blurred modern "
    "{location_hint} {bg_context} with warm wooden accents and a hint of "
    "window light visible behind them. Natural window light from the side, "
    "warm color palette with subtle cool accent ({theme_accent}) in the "
    "background shadows. The mood is {mood}, representing someone who "
    "{personality_hint}. Editorial corporate photography style, shallow "
    "depth of field, centered composition with head and shoulders "
    "visible. {style}"
)


# ─── Data classes ──────────────────────────────────────────────────────
@dataclass
class ImageSpec:
    """One image to generate, with its target path in lp_content JSON."""
    key: str           # stable identifier for logging + filename (e.g., "hero", "pos0")
    jsonb_path: str    # dotted path in lp_content (e.g., "hero.bg_image")
    prompt: str        # the full Gemini prompt, pre-rendered


@dataclass
class ImagePipelineResult:
    """Per-image result with URL, size, timing."""
    key: str
    ok: bool
    jsonb_path: str = ""
    url: str = ""
    filename: str = ""
    local_path: str = ""
    size_bytes: int = 0
    elapsed_sec: float = 0.0
    error: str = ""


# ─── Gender alternation helper ─────────────────────────────────────────
# For LPs with 2+ positions, alternate the gender of the position imagery
# so we don't have 3 photos of men or 3 of women in a row.
_GENDER_ROTATION = ["woman", "man", "woman", "man", "woman", "man"]


class ImagePipeline:
    """
    Orchestrates concept-aware LP image generation for a single client.

    Usage:
        pipe = ImagePipeline(slug="cloq", client_name="株式会社CLOQ", ...)
        results = pipe.generate_all()  # blocks ~22s for typical LP
        # results is a dict: { jsonb_path: ImagePipelineResult }
    """

    def __init__(
        self,
        slug: str,
        client_name: str,
        industry: str,
        theme_accent: str,
        company_concepts: dict,
        openings: list[dict],
        *,
        generate_employee_headshots: bool = True,
        output_dir: str = OUTPUT_DIR,
        public_base: str = PUBLIC_BASE,
    ):
        if not slug or not slug.replace("-", "").isalnum():
            raise ValueError(f"invalid slug: {slug!r}")
        if not openings:
            raise ValueError("at least one opening is required")
        self.slug = slug
        self.client_name = client_name
        self.industry = industry
        self.theme_accent = theme_accent or "#2673b8"
        self.concepts = company_concepts
        self.openings = openings
        self.gen_employees = generate_employee_headshots
        self.output_dir = output_dir
        self.public_base = public_base
        self._gemini_key: Optional[str] = None

        # Derived defaults from company_concepts
        self.location_hint = company_concepts.get("location_hint", "Kyoto, Japan")
        self.business_type = company_concepts.get(
            "business_type", "professional services"
        )
        # Translate business type to a scene-appropriate English phrase for
        # the whiteboard diagram in the hero shot
        self.business_workflow = self._infer_workflow(industry)
        self.values_en = self._format_values()
        self.conversation_topic = company_concepts.get(
            "conversation_topic", "honest work"
        )

        os.makedirs(self.output_dir, exist_ok=True)

    # ─── Internal helpers ──────────────────────────────────────────────

    def _get_key(self) -> str:
        if self._gemini_key is None:
            self._gemini_key = _get_gemini_key()
        return self._gemini_key

    def _infer_workflow(self, industry: str) -> str:
        """Map industry to a scene-appropriate workflow topic for the hero."""
        table = {
            "採用コンサルティング": "recruitment workflow",
            "人材紹介": "candidate matching",
            "人材紹介事業": "candidate matching",
            "recruitment consulting": "recruitment workflow",
            "製造業": "production process",
            "manufacturing": "production process",
            "IT": "product roadmap",
            "ソフトウェア": "product roadmap",
            "software": "product roadmap",
            "建設業": "project schedule",
            "construction": "project schedule",
            "広告": "campaign timeline",
            "advertising": "campaign timeline",
            "マーケティング": "campaign timeline",
            "marketing": "campaign timeline",
        }
        for k, v in table.items():
            if k in industry:
                return v
        return "business workflow"

    def _format_values(self) -> str:
        """Render company_concepts.values[] as a natural English phrase."""
        values = self.concepts.get("values", [])
        if not values:
            return "honest communication and flat hierarchy"
        # Japanese values get a parenthetical English gloss
        value_glosses = {
            "本音": "honest communication (本音)",
            "フラット": "flat hierarchy",
            "フラットチーム": "flat team culture",
            "在宅可": "flexible remote work",
            "服装自由": "casual dress code",
            "実務": "hands-on work",
            "現場": "on-the-ground execution",
            "素直": "genuine openness",
        }
        glossed = [value_glosses.get(v, v) for v in values[:3]]
        return " and ".join(glossed)

    # ─── Prompt builders ───────────────────────────────────────────────

    def _build_hero_prompt(self) -> str:
        return HERO_PROMPT_TEMPLATE.format(
            location_hint=self.location_hint,
            business_type_en=self.business_type,
            business_workflow=self.business_workflow,
            theme_accent=self.theme_accent,
            style=_SHARED_STYLE_BLOCK,
        )

    def _build_about_prompt(self) -> str:
        return ABOUT_PROMPT_TEMPLATE.format(
            location_hint=self.location_hint,
            conversation_topic=self.conversation_topic,
            values_en=self.values_en,
            theme_accent=self.theme_accent,
            style=_SHARED_STYLE_BLOCK,
        )

    def _build_position_prompt(self, idx: int, opening: dict) -> str:
        """
        Build a prompt for a position image. Tries to match the scene to the
        role semantically (customer-facing vs writer vs engineer etc.) based
        on the role title keywords.
        """
        gender = _GENDER_ROTATION[idx % len(_GENDER_ROTATION)]
        title = opening.get("title", "")
        role_en = opening.get("en", "team member")

        # Role-aware environment + action
        environment_detail = (
            "Desk has an open notebook with handwritten notes, a white "
            "ceramic coffee cup, and a small potted plant."
        )
        light_side = "left"
        outfit = (
            "a simple cream-colored sweater over a collared shirt"
            if gender == "woman"
            else "a charcoal merino v-neck sweater over a simple white t-shirt"
        )

        # Keyword-based role_action heuristic — picks a scene that fits
        # what the employee would actually be doing day-to-day
        title_lower = title.lower() + " " + role_en.lower()
        if any(k in title for k in ["支援", "サポート", "採用"]) or "support" in title_lower or "recruit" in title_lower:
            role_action = (
                "engaged in a video call with a job candidate (visible as a "
                "blurred silhouette on the laptop screen, no identifying "
                "features), gesturing warmly while explaining something, "
                "genuine professional smile"
            )
        elif any(k in title for k in ["ライター", "クリエイター", "コピー"]) or "writ" in title_lower or "copy" in title_lower or "content" in title_lower:
            role_action = (
                "deep in creative focus at a standing desk writing ideas in "
                "a paper notebook with a fountain pen while a laptop beside "
                "them shows a text editor with blurred copy-in-progress. "
                "Post-it notes with scribbled word ideas (text blurred) on "
                "a cork board behind them"
            )
            environment_detail = (
                "Warm morning light streams from a large window overlooking "
                "a traditional " + self.location_hint + " street."
            )
        elif any(k in title_lower for k in ["engineer", "developer", "エンジニア", "開発"]):
            role_action = (
                "focused on dual monitors showing code (text blurred, not "
                "readable), one hand on a mechanical keyboard, expression "
                "of quiet concentration"
            )
        elif any(k in title_lower for k in ["design", "デザイン"]):
            role_action = (
                "sketching a concept on a drawing tablet with a stylus, "
                "design software open on a monitor beside them (UI blurred)"
            )
        elif any(k in title_lower for k in ["sales", "営業", "セールス"]):
            role_action = (
                "on a phone call while looking at a laptop screen, taking "
                "notes on a paper notepad, warm confident expression"
            )
        else:
            # Generic fallback: meeting / collaboration scene
            role_action = (
                "in the middle of focused work at a modern office desk, "
                "engaged with a laptop and notebook, calm professional "
                "expression"
            )

        return POSITION_PROMPT_TEMPLATE.format(
            gender=gender,
            location_hint=self.location_hint,
            role_name=title,
            role_en=role_en,
            role_action=role_action,
            environment_detail=environment_detail,
            light_side=light_side,
            outfit=outfit,
            theme_accent=self.theme_accent,
            style=_SHARED_STYLE_BLOCK,
        )

    def _build_employee_prompt(self, idx: int, opening: dict) -> str:
        """
        Build a headshot prompt for a placeholder employee. Alternates gender
        with the position images (if position 0 shows a woman, employee 0's
        headshot is also a woman for consistency).
        """
        gender = _GENDER_ROTATION[idx % len(_GENDER_ROTATION)]
        title = opening.get("title", "").lower()

        # Role-matched appearance
        if "クリエイター" in title or "writ" in title or "copy" in title:
            # Creative writer vibe
            if gender == "woman":
                hair_desc = "Shoulder-length black hair in a natural wavy style"
                appearance = "minimal makeup, warm skin tone"
                outfit = "a simple charcoal turtleneck with minimal jewelry"
                expression = "thoughtful but warm expression"
                mood = "creative, focused, genuine"
                personality_hint = "takes craft seriously"
                bg_context = "cafe or co-working space"
            else:
                hair_desc = "Short neatly-cut black hair, clean-shaven, wearing glasses with thin modern frames"
                appearance = "warm skin tone, relaxed posture"
                outfit = "a charcoal merino v-neck sweater over a white t-shirt"
                expression = "thoughtful but warm expression"
                mood = "creative, focused, genuine"
                personality_hint = "thinks deeply about their writing"
                bg_context = "cafe or co-working space"
            gaze = "looking directly at the camera with a subtle smile"
        else:
            # Customer-facing / support / general professional vibe
            if gender == "woman":
                hair_desc = "Shoulder-length black hair in a natural style"
                appearance = "minimal makeup, warm skin tone"
                outfit = "a soft cream-colored turtleneck sweater with a simple silver necklace"
                expression = "natural warm smile"
                mood = "genuine, approachable, and confident"
                personality_hint = "genuinely cares about helping people"
                bg_context = "office interior"
            else:
                hair_desc = "Short neatly-cut black hair, clean-shaven"
                appearance = "warm skin tone, open posture"
                outfit = "a navy cardigan over a simple white dress shirt"
                expression = "natural warm smile"
                mood = "genuine, approachable, and confident"
                personality_hint = "genuinely cares about helping people"
                bg_context = "office interior"
            gaze = "looking slightly off-camera in a candid moment"

        return EMPLOYEE_HEADSHOT_TEMPLATE.format(
            gender=gender,
            location_hint=self.location_hint,
            expression=expression,
            gaze=gaze,
            hair_desc=hair_desc,
            appearance_detail=appearance,
            outfit=outfit,
            bg_context=bg_context,
            theme_accent=self.theme_accent,
            mood=mood,
            personality_hint=personality_hint,
            style=_SHARED_STYLE_BLOCK,
        )

    # ─── Spec assembly ─────────────────────────────────────────────────

    def _assemble_specs(self) -> list[ImageSpec]:
        """Return the full list of ImageSpecs to generate for this LP."""
        specs = [
            ImageSpec(
                key="hero",
                jsonb_path="hero.bg_image",
                prompt=self._build_hero_prompt(),
            ),
            ImageSpec(
                key="about",
                jsonb_path="about.photo",
                prompt=self._build_about_prompt(),
            ),
        ]
        for i, opening in enumerate(self.openings):
            specs.append(
                ImageSpec(
                    key=f"pos{i}",
                    jsonb_path=f"openings.items.{i}.image",
                    prompt=self._build_position_prompt(i, opening),
                )
            )
            if self.gen_employees:
                specs.append(
                    ImageSpec(
                        key=f"emp{i}",
                        jsonb_path=f"openings.items.{i}.detail.employee.photo",
                        prompt=self._build_employee_prompt(i, opening),
                    )
                )
        return specs

    # ─── Generation ────────────────────────────────────────────────────

    def _generate_one(self, spec: ImageSpec) -> ImagePipelineResult:
        """Generate a single image via Gemini REST API."""
        t0 = time.time()
        url = f"{API_BASE}/models/{MODEL}:generateContent?key={self._get_key()}"
        body = {"contents": [{"parts": [{"text": spec.prompt}]}]}
        req = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT_SEC) as resp:
                data = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            err = e.read().decode("utf-8", errors="replace")[:500]
            return ImagePipelineResult(
                key=spec.key, ok=False, jsonb_path=spec.jsonb_path,
                error=f"HTTP {e.code}: {err}",
                elapsed_sec=round(time.time() - t0, 1),
            )
        except Exception as e:
            return ImagePipelineResult(
                key=spec.key, ok=False, jsonb_path=spec.jsonb_path,
                error=f"{type(e).__name__}: {e}",
                elapsed_sec=round(time.time() - t0, 1),
            )

        candidates = data.get("candidates", [])
        if not candidates:
            return ImagePipelineResult(
                key=spec.key, ok=False, jsonb_path=spec.jsonb_path,
                error=f"no candidates (prompt may have been blocked): {json.dumps(data)[:200]}",
                elapsed_sec=round(time.time() - t0, 1),
            )

        parts = candidates[0].get("content", {}).get("parts", [])
        image_part = next((p for p in parts if "inlineData" in p), None)
        if not image_part:
            text_parts = [p.get("text", "")[:100] for p in parts if "text" in p]
            return ImagePipelineResult(
                key=spec.key, ok=False, jsonb_path=spec.jsonb_path,
                error=f"no image in response, only text: {text_parts}",
                elapsed_sec=round(time.time() - t0, 1),
            )

        mime = image_part["inlineData"].get("mimeType", "image/jpeg")
        raw = base64.b64decode(image_part["inlineData"]["data"])
        ext = "jpg" if "jpeg" in mime else ("png" if "png" in mime else "bin")
        h = hashlib.sha1(f"{self.slug}-{spec.key}-{time.time()}".encode()).hexdigest()[:12]
        filename = f"{self.slug}_{spec.key}_{h}.{ext}"
        path = os.path.join(self.output_dir, filename)
        with open(path, "wb") as f:
            f.write(raw)

        return ImagePipelineResult(
            key=spec.key,
            ok=True,
            jsonb_path=spec.jsonb_path,
            url=f"{self.public_base}/{filename}",
            filename=filename,
            local_path=path,
            size_bytes=len(raw),
            elapsed_sec=round(time.time() - t0, 1),
        )

    def generate_all(self, max_parallel: int = 6) -> dict[str, ImagePipelineResult]:
        """
        Generate every image for this LP in parallel and return a dict
        keyed by jsonb_path (so the caller can directly feed it into a
        jsonb_set UPDATE statement).

        Also duplicates the `openings.items[N].image` result into
        `openings.items[N].detail.hero_bg` since those are two separate
        fields in the lp_content schema that should render the same photo.
        """
        specs = self._assemble_specs()
        results: dict[str, ImagePipelineResult] = {}

        print(
            f"[image_pipeline] {self.slug}: generating {len(specs)} images "
            f"via {MODEL}, max_parallel={max_parallel}",
            flush=True,
        )
        t0 = time.time()
        with ThreadPoolExecutor(max_workers=max_parallel) as pool:
            futures = {pool.submit(self._generate_one, s): s for s in specs}
            for future in as_completed(futures):
                spec = futures[future]
                try:
                    result = future.result(timeout=REQUEST_TIMEOUT_SEC + 20)
                except Exception as e:
                    result = ImagePipelineResult(
                        key=spec.key, ok=False,
                        jsonb_path=spec.jsonb_path,
                        error=f"future error: {e}",
                    )
                results[result.jsonb_path] = result
                status = "✓" if result.ok else "✗"
                print(
                    f"  {status} {spec.key:6s} [{result.elapsed_sec:5.1f}s] "
                    f"{result.jsonb_path:48s} "
                    f"{'→ ' + result.url if result.ok else '— ' + result.error[:80]}",
                    flush=True,
                )

        # Duplicate opening.image URLs into opening.detail.hero_bg paths
        # since those are two separate schema fields that should show the
        # same image on the main LP and the job detail page respectively
        for i in range(len(self.openings)):
            src = f"openings.items.{i}.image"
            dst = f"openings.items.{i}.detail.hero_bg"
            if src in results and results[src].ok:
                r = results[src]
                results[dst] = ImagePipelineResult(
                    key=f"{r.key}_detail_hero",
                    ok=True,
                    jsonb_path=dst,
                    url=r.url,
                    filename=r.filename,
                    local_path=r.local_path,
                    size_bytes=r.size_bytes,
                    elapsed_sec=0.0,  # duplicate, no generation cost
                )

        total = time.time() - t0
        ok_count = sum(1 for r in results.values() if r.ok)
        print(
            f"[image_pipeline] {self.slug}: {ok_count}/{len(results)} "
            f"paths populated in {total:.1f}s wall clock",
            flush=True,
        )
        return results

    def build_update_sql(self, results: dict[str, ImagePipelineResult]) -> str:
        """
        Given a results dict, build a single SQL UPDATE statement that
        jsonb_sets every successful image URL into the cloq lp_content row.

        Chains jsonb_set calls from innermost to outermost. Skips failed
        generations (jsonb path is left unchanged).
        """
        successful = [(path, r) for path, r in results.items() if r.ok]
        if not successful:
            raise RuntimeError("no successful image generations — nothing to update")

        # Build the chained jsonb_set expression
        expr = "content"
        for jsonb_path, r in successful:
            # Convert dotted path like "openings.items.0.image" to
            # postgres jsonb path array like '{openings,items,0,image}'
            parts = jsonb_path.split(".")
            pg_path = "{" + ",".join(parts) + "}"
            # The new value is the URL as a jsonb string literal
            # Dollar-quote the URL to avoid escaping issues
            expr = (
                f"jsonb_set(\n    {expr},\n    '{pg_path}',\n    "
                f"$$\"{r.url}\"$$::jsonb\n  )"
            )

        return f"""-- Auto-generated by image_pipeline.py for slug={self.slug!r}
-- Replaces {len(successful)} image paths in lp_content.
update public.lp_content
set content = {expr},
    updated_at = now()
where lp_slug = '{self.slug}';"""


# ─── CLI entry point ───────────────────────────────────────────────────
def _cli():
    """
    Command-line entry point. Reads JSON config from stdin and runs the
    pipeline. Used by bootstrap.py via subprocess, so bootstrap.py can
    stay in its own process and call image_pipeline.py as a clean boundary.

    Input JSON (on stdin):
        {
            "slug": "cloq",
            "client_name": "株式会社CLOQ",
            "industry": "採用コンサルティング",
            "theme_accent": "#2673b8",
            "company_concepts": {
                "business_type": "人材紹介事業",
                "values": ["本音", "フラットチーム", "実務"],
                "location_hint": "Kyoto, Japan",
                "conversation_topic": "recruitment strategy"
            },
            "openings": [
                {"title": "採用支援スタッフ", "en": "Recruitment Support"},
                {"title": "採用クリエイター", "en": "Recruitment Writer"}
            ],
            "generate_employee_headshots": true
        }

    Output JSON (on stdout):
        {
            "ok": true,
            "slug": "cloq",
            "urls": {
                "hero.bg_image": "https://...",
                "about.photo": "https://...",
                ...
            },
            "update_sql": "update public.lp_content set ..."
        }
    """
    cfg = json.load(sys.stdin)
    pipe = ImagePipeline(
        slug=cfg["slug"],
        client_name=cfg["client_name"],
        industry=cfg.get("industry", ""),
        theme_accent=cfg.get("theme_accent", "#2673b8"),
        company_concepts=cfg.get("company_concepts", {}),
        openings=cfg.get("openings", []),
        generate_employee_headshots=cfg.get("generate_employee_headshots", True),
    )
    results = pipe.generate_all()
    urls = {path: r.url for path, r in results.items() if r.ok}
    errors = {path: r.error for path, r in results.items() if not r.ok}
    output = {
        "ok": all(r.ok for r in results.values()),
        "slug": pipe.slug,
        "urls": urls,
        "errors": errors,
        "update_sql": pipe.build_update_sql(results) if urls else "",
    }
    print(json.dumps(output, ensure_ascii=False, indent=2))
    sys.exit(0 if output["ok"] else 1)


if __name__ == "__main__":
    _cli()
